### ISSUE TITLE
项目安装完npm的依赖后运行报错Error: Cannot find module 'fork-ts-checker-webpack-plugin-v5'

### ISSUE THREAD

**Issue by FrozenLemonTee** [blacktunes/voices-button-cli#1]
ERROR  Error: Cannot find module 'fork-ts-checker-webpack-plugin-v5'
Require stack:
- D:\FrozenLemonTee\Arbeit\WebProject\ciyanaButton\ciyana-button\node_modules\_@vue_cli-plugin-typescript@4.5.11@@vue\cli-plugin-typescript\index.js
- D:\FrozenLemonTee\Arbeit\WebProject\ciyanaButton\ciyana-button\node_modules\_@vue_cli-service@4.5.11@@vue\cli-service\lib\Service.js
- D:\FrozenLemonTee\Arbeit\WebProject\ciyanaButton\ciyana-button\node_modules\_@vue_cli-service@4.5.11@@vue\cli-service\bin\vue-cli-service.js
Error: Cannot find module 'fork-ts-checker-webpack-plugin-v5'
Require stack:
- D:\FrozenLemonTee\Arbeit\WebProject\ciyanaButton\ciyana-button\node_modules\_@vue_cli-plugin-typescript@4.5.11@@vue\cli-plugin-typescript\index.js
- D:\FrozenLemonTee\Arbeit\WebProject\ciyanaButton\ciyana-button\node_modules\_@vue_cli-service@4.5.11@@vue\cli-service\lib\Service.js
- D:\FrozenLemonTee\Arbeit\WebProject\ciyanaButton\ciyana-button\node_modules\_@vue_cli-service@4.5.11@@vue\cli-service\bin\vue-cli-service.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at D:\FrozenLemonTee\Arbeit\WebProject\ciyanaButton\ciyana-button\node_modules\_@vue_cli-plugin-typescript@4.5.11@@vue\cli-plugin-typescript\index.js:89:16
    at D:\FrozenLemonTee\Arbeit\WebProject\ciyanaButton\ciyana-button\node_modules\_@vue_cli-service@4.5.11@@vue\cli-service\lib\Service.js:236:40
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (D:\FrozenLemonTee\Arbeit\WebProject\ciyanaButton\ciyana-button\node_modules\_@vue_cli-service@4.5.11@@vue\cli-serv
ice\lib\Service.js:236:26)
    at Service.resolveWebpackConfig (D:\FrozenLemonTee\Arbeit\WebProject\ciyanaButton\ciyana-button\node_modules\_@vue_cli-service@4.5.11@@vue\cli-service\lib\S
ervice.js:240:48)
    at PluginAPI.resolveWebpackConfig (D:\FrozenLemonTee\Arbeit\WebProject\ciyanaButton\ciyana-button\node_modules\_@vue_cli-service@4.5.11@@vue\cli-service\lib
\PluginAPI.js:132:25)
    at serve (D:\FrozenLemonTee\Arbeit\WebProject\ciyanaButton\ciyana-button\node_modules\_@vue_cli-service@4.5.11@@vue\cli-service\lib\commands\serve.js:75:31)
    at Service.run (D:\FrozenLemonTee\Arbeit\WebProject\ciyanaButton\ciyana-button\node_modules\_@vue_cli-service@4.5.11@@vue\cli-service\lib\Service.js:230:12)
    at Object.<anonymous> (D:\FrozenLemonTee\Arbeit\WebProject\ciyanaButton\ciyana-button\node_modules\_@vue_cli-service@4.5.11@@vue\cli-service\bin\vue-cli-ser
vice.js:36:9)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
npm ERR! code 1
npm ERR! path D:\FrozenLemonTee\Arbeit\WebProject\ciyanaButton\ciyana-button
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c vue-cli-service serve

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Local\npm-cache\_logs\2021-03-14T05_04_03_593Z-debug.log

**Comment by blacktunes** [comment]
我等下看看

**Comment by blacktunes** [comment]
刚测试了一下，使用`yarn`和`npm`都能正常安装依赖和运行，能提供一下更多信息吗。
或者尝试一下`npm i fork-ts-checker-webpack-plugin -D`/``yarn add fork-ts-checker-webpack-plugin -D``

**Comment by FrozenLemonTee** [comment]
**是这样的，一开始用命令行生成项目后，我先是用`npm install`，后报错：**

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: ciyana-button@1.0.0
npm ERR! Found: eslint@7.22.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.9.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^5.0.0 || ^6.0.0" from @typescript-eslint/parser@2.34.0
npm ERR! node_modules/@typescript-eslint/parser
npm ERR!   dev @typescript-eslint/parser@"^2.34.0" from the root project
npm ERR!   peer @typescript-eslint/parser@"^2.0.0" from @typescript-eslint/eslint-plugin@2.34.0
npm ERR!   node_modules/@typescript-eslint/eslint-plugin
npm ERR!     dev @typescript-eslint/eslint-plugin@"^2.34.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Lenovo\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Local\npm-cache\_logs\2021-03-14T06_25_44_726Z-debug.log

**后换成国内镜像`cnpm install`，安装完以后pychram对package.json的检查是没问题的，不过途中有输出一些警告：**

- [4/26] Installing mime-db@1.46.0[fork-ts-checker-webpack-plugin-v5@npm:fork-ts-checker-webpack-plugin@^5.0.11] optional install error: Error: Unsupported URL Typ
e: npm:fork-ts-checker-webpack-plugin@^5.0.11
    at parseUrl (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm-package-arg\npa.js:186:13)
    at npa (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm-package-arg\npa.js:79:12)
    at _install (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install.js:62:11)
    at _install.next (<anonymous>)
    at onFulfilled (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:65:19)
    at C:\Users\Lenovo\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at co (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:50:10)
    at toPromise (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:118:63)
    at next (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:99:29)
/ [12/26] Installing postcss@^7.0.14platform unsupported @vue/cli-plugin-typescript@4.5.11 › fork-ts-checker-webpack-plugin@3.1.1 › chokidar@3.5.1 › fsevents@~2.3.
1 Package require os(darwin) not compatible with your platform(win32)
- [12/26] Installing @babel/preset-modules@^0.1.4[fsevents@~2.3.1] optional install error: Package require os(darwin) not compatible with your platform(win32)
- [12/26] Installing fsevents@^1.2.7platform unsupported @vue/cli-plugin-babel@4.5.11 › webpack@4.46.0 › watchpack@1.7.5 › watchpack-chokidar2@2.0.1 › chokidar@2.1
.8 › fsevents@^1.2.7 Package require os(darwin) not compatible with your platform(win32)
\ [12/26] Installing portfinder@^1.0.26[fsevents@^1.2.7] optional install error: Package require os(darwin) not compatible with your platform(win32)
- [15/26] Installing webpack-merge@^4.2.2[vue-loader-v16@npm:vue-loader@^16.1.0] optional install error: Error: Unsupported URL Type: npm:vue-loader@^16.1.0
    at parseUrl (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm-package-arg\npa.js:186:13)
    at npa (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm-package-arg\npa.js:79:12)
    at _install (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install.js:62:11)
    at _install.next (<anonymous>)
    at onFulfilled (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:65:19)
    at C:\Users\Lenovo\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at co (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:50:10)
    at toPromise (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:118:63)
    at next (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:99:29)
√ Installed 26 packages
√ Linked 1025 latest versions
[1/3] scripts.install @vue/cli-plugin-eslint@4.5.11 › yorkie@^2.0.0 run "node bin/install.js", root: "D:\\FrozenLemonTee\\Arbeit\\WebProject\\ciyana-button\\ciyana
-button\\node_modules\\_yorkie@2.0.0@yorkie"
setting up Git hooks
can't find .git directory, skipping Git hooks installation
[1/3] scripts.install @vue/cli-plugin-eslint@4.5.11 › yorkie@^2.0.0 finished in 244ms
[2/3] scripts.postinstall @vue/cli-service@4.5.11 › webpack-bundle-analyzer@3.9.0 › ejs@^2.6.1 run "node ./postinstall.js", root: "D:\\FrozenLemonTee\\Arbeit\\WebP
roject\\ciyana-button\\ciyana-button\\node_modules\\_ejs@2.7.4@ejs"
Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

[2/3] scripts.postinstall @vue/cli-service@4.5.11 › webpack-bundle-analyzer@3.9.0 › ejs@^2.6.1 finished in 190ms
[3/3] scripts.postinstall @vue/cli-plugin-babel@4.5.11 › @vue/babel-preset-app@4.5.11 › core-js@^3.6.5 run "node -e \"try{require('./postinstall')}catch(e){}\"", r
oot: "D:\\FrozenLemonTee\\Arbeit\\WebProject\\ciyana-button\\ciyana-button\\node_modules\\_core-js@3.9.1@core-js"
Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

[3/3] scripts.postinstall @vue/cli-plugin-babel@4.5.11 › @vue/babel-preset-app@4.5.11 › core-js@^3.6.5 finished in 253ms
√ Run 3 scripts
peerDependencies link ajv@6.12.6 in D:\FrozenLemonTee\Arbeit\WebProject\ciyana-button\ciyana-button\node_modules\_ajv-keywords@3.5.2@ajv-keywords unmet with D:\Fro
zenLemonTee\Arbeit\WebProject\ciyana-button\ciyana-button\node_modules\ajv(7.2.1)
peerDependencies link ajv@6.12.6 in D:\FrozenLemonTee\Arbeit\WebProject\ciyana-button\ciyana-button\node_modules\_ajv-errors@1.0.1@ajv-errors unmet with D:\FrozenL
emonTee\Arbeit\WebProject\ciyana-button\ciyana-button\node_modules\ajv(7.2.1)
peerDependencies WARNING @vue/cli-plugin-eslint@~4.5.6 requires a peer of eslint@>= 1.6.0 < 7.0.0 but eslint@7.22.0 was installed
peerDependencies WARNING @typescript-eslint/parser@^2.34.0 requires a peer of eslint@^5.0.0 || ^6.0.0 but eslint@7.22.0 was installed
peerDependencies WARNING @typescript-eslint/eslint-plugin@^2.34.0 requires a peer of eslint@^5.0.0 || ^6.0.0 but eslint@7.22.0 was installed
peerDependencies WARNING @vue/cli-service@~4.5.6 requires a peer of vue-template-compiler@^2.0.0 but none was installed
peerDependencies WARNING @vue/cli-plugin-eslint@4.5.11 › eslint-loader@^2.2.1 requires a peer of eslint@>=1.6.0 <7.0.0 but eslint@7.22.0 was installed
deprecate @vue/cli-plugin-babel@4.5.11 › @vue/cli-shared-utils@4.5.11 › request@^2.88.2 request has been deprecated, see https://github.com/request/request/issues/
3142
deprecate @vue/cli-plugin-babel@4.5.11 › @vue/cli-shared-utils@4.5.11 › @hapi/joi@^15.0.1 Switch to 'npm install joi'
deprecate @vue/cli-plugin-babel@4.5.11 › @vue/cli-shared-utils@4.5.11 › request@2.88.2 › har-validator@~5.1.3 this library is no longer supported
deprecate @vue/cli-service@4.5.11 › @vue/preload-webpack-plugin@1.1.2 › html-webpack-plugin@^3.2.0 3.x is no longer supported
deprecate @vue/cli-plugin-babel@4.5.11 › @vue/cli-shared-utils@4.5.11 › @hapi/joi@15.1.1 › @hapi/bourne@1.x.x This version has been deprecated and is no longer sup
ported or maintained
deprecate @vue/cli-plugin-babel@4.5.11 › @vue/cli-shared-utils@4.5.11 › @hapi/joi@15.1.1 › @hapi/topo@3.x.x This version has been deprecated and is no longer suppo
rted or maintained
deprecate @vue/cli-plugin-babel@4.5.11 › @vue/cli-shared-utils@4.5.11 › @hapi/joi@15.1.1 › @hapi/address@2.x.x This version has been deprecated and is no longer su
pported or maintained
deprecate @vue/cli-plugin-babel@4.5.11 › @vue/cli-shared-utils@4.5.11 › @hapi/joi@15.1.1 › @hapi/hoek@8.x.x This version has been deprecated and is no longer suppo
rted or maintained
deprecate babel-eslint@^10.1.0 babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
deprecate @vue/cli-plugin-eslint@4.5.11 › globby@9.2.0 › fast-glob@2.2.7 › micromatch@3.1.10 › braces@2.3.2 › snapdragon@0.8.2 › source-map-resolve@0.5.3 › urix@^0
.1.0 Please see https://github.com/lydell/urix#deprecated
deprecate @vue/cli-plugin-eslint@4.5.11 › globby@9.2.0 › fast-glob@2.2.7 › micromatch@3.1.10 › braces@2.3.2 › snapdragon@0.8.2 › source-map-resolve@0.5.3 › resolve
-url@^0.2.1 https://github.com/lydell/resolve-url#deprecated
deprecate @vue/cli-plugin-babel@4.5.11 › webpack@4.46.0 › watchpack@1.7.5 › watchpack-chokidar2@2.0.1 › chokidar@^2.1.8 Chokidar 2 will break on node v14+. Upgrade
 to chokidar 3 with 15x less dependencies.
deprecate @vue/cli-plugin-babel@4.5.11 › webpack@4.46.0 › watchpack@1.7.5 › watchpack-chokidar2@2.0.1 › chokidar@2.1.8 › fsevents@^1.2.7 fsevents 1 will break on n
ode v14+ and could be using insecure binaries. Upgrade to fsevents 2.
Recently updated (since 2021-03-07): 23 packages (detail see file D:\FrozenLemonTee\Arbeit\WebProject\ciyana-button\ciyana-button\node_modules\.recently_updates.tx
t)
  Today:
    → fork-ts-checker-webpack-plugin@5.2.1 › cosmiconfig@6.0.0 › yaml@^1.7.2(1.10.2) (05:02:56)
√ All packages installed (1255 packages installed from npm registry, used 17s(network 15s), speed 220.18kB/s, json 1051(3.32MB), tarball 0B)

**运行后报错：**

Error: Cannot find module 'vue-loader-v16/package.json'
Require stack:
- D:\FrozenLemonTee\Arbeit\WebProject\ciyana-button\ciyana-button\node_modules\_@vue_cli-service@4.5.11@@vue\cli-service\lib\config\base.js
- D:\FrozenLemonTee\Arbeit\WebProject\ciyana-button\ciyana-button\node_modules\_@vue_cli-service@4.5.11@@vue\cli-service\lib\Service.js
- D:\FrozenLemonTee\Arbeit\WebProject\ciyana-button\ciyana-button\node_modules\_@vue_cli-service@4.5.11@@vue\cli-service\bin\vue-cli-service.js
Error: Cannot find module 'vue-loader-v16/package.json'
Require stack:
- D:\FrozenLemonTee\Arbeit\WebProject\ciyana-button\ciyana-button\node_modules\_@vue_cli-service@4.5.11@@vue\cli-service\lib\config\base.js
- D:\FrozenLemonTee\Arbeit\WebProject\ciyana-button\ciyana-button\node_modules\_@vue_cli-service@4.5.11@@vue\cli-service\lib\Service.js
- D:\FrozenLemonTee\Arbeit\WebProject\ciyana-button\ciyana-button\node_modules\_@vue_cli-service@4.5.11@@vue\cli-service\bin\vue-cli-service.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at D:\FrozenLemonTee\Arbeit\WebProject\ciyana-button\ciyana-button\node_modules\_@vue_cli-service@4.5.11@@vue\cli-service\lib\config\base.js:114:23
    at D:\FrozenLemonTee\Arbeit\WebProject\ciyana-button\ciyana-button\node_modules\_@vue_cli-service@4.5.11@@vue\cli-service\lib\Service.js:236:40
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (D:\FrozenLemonTee\Arbeit\WebProject\ciyana-button\ciyana-button\node_modules\_@vue_cli-service@4.5.11@@vue\cli-ser
vice\lib\Service.js:236:26)
    at Service.resolveWebpackConfig (D:\FrozenLemonTee\Arbeit\WebProject\ciyana-button\ciyana-button\node_modules\_@vue_cli-service@4.5.11@@vue\cli-service\lib\
Service.js:240:48)
    at PluginAPI.resolveWebpackConfig (D:\FrozenLemonTee\Arbeit\WebProject\ciyana-button\ciyana-button\node_modules\_@vue_cli-service@4.5.11@@vue\cli-service\li
b\PluginAPI.js:132:25)
npm ERR! code 1
npm ERR! path D:\FrozenLemonTee\Arbeit\WebProject\ciyana-button\ciyana-button
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c vue-cli-service serve

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Local\npm-cache\_logs\2021-03-14T06_50_56_674Z-debug.log

**按照提示安装vue-loader-v16插件以后再运行便又跳出一楼处的错误**

**Comment by blacktunes** [comment]
要不尝试一下删除`node_modules`文件夹然后使用`yarn`安装依赖

**Comment by FrozenLemonTee** [comment]
运行成功了，非常感谢！
顺便问一下按钮的样式只有默认的吗？

**Comment by blacktunes** [comment]
可以简单修改的基本就只有创建时的那些选项，需要其它样式只能靠自己修改代码了
